export function convertDate(date) {
    // use when time is generated by frontend
    date =
        date.toLocaleString("default", { month: "short" }) +
        "," +
        date.getDate() +
        " " +
        date.getFullYear();
    return date;
}

export function newConvertDate(date) {
    // use when time is received as string from backend
    var new_date = new Date(date)
    var userTimezoneOffset = new_date.getTimezoneOffset() * 60000;
    new_date = new Date(new_date.getTime() + userTimezoneOffset);
    new_date =
        new_date.toLocaleString("default", { month: "short" }) +
        " " +
        new_date.getDate() +
        ", " +
        new_date.getFullYear();
    return new_date;
}

export function newLocalDate(date) {
    var new_date = new Date(date)
    var userTimezoneOffset = new_date.getTimezoneOffset() * 60000;
    new_date = new Date(new_date.getTime() + userTimezoneOffset);
    return new_date;
}

export const getEDTDate = () => {
    const now = new Date();

    // Convert to UTC time
    const utcTime = now.getTime() + now.getTimezoneOffset() * 60000;

    // Adjust for EDT (UTC-4)
    const edtTime = new Date(utcTime + (3600000 * -4));

    // Extract date and time parts
    const month = String(edtTime.getMonth() + 1).padStart(2, '0');
    const day = String(edtTime.getDate()).padStart(2, '0');
    const year = edtTime.getFullYear();
    const hours = String(edtTime.getHours()).padStart(2, '0');
    const minutes = String(edtTime.getMinutes()).padStart(2, '0');
    const seconds = String(edtTime.getSeconds()).padStart(2, '0');

    return `${month}/${day}/${year} ${hours}:${minutes}:${seconds}`;
};